const { store, mode } = require('./store');

const BASIC_TABLE_SPECS = {
  "users": [
    [
      "user_id",
      "text primary key"
    ],
    [
      "username",
      "text"
    ],
    [
      "password",
      "text"
    ],
    [
      "full_name",
      "text"
    ],
    [
      "designation",
      "text"
    ],
    [
      "role",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "tl_user_id",
      "text"
    ],
    [
      "tl_code",
      "text"
    ],
    [
      "tl_name",
      "text"
    ],
    [
      "is_active",
      "text"
    ],
    [
      "theme_name",
      "text"
    ],
    [
      "email",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ]
  ],
  "candidates": [
    [
      "candidate_id",
      "text primary key"
    ],
    [
      "call_connected",
      "text"
    ],
    [
      "looking_for_job",
      "text"
    ],
    [
      "full_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "location",
      "text"
    ],
    [
      "qualification",
      "text"
    ],
    [
      "course_name",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "preferred_location",
      "text"
    ],
    [
      "in_hand_salary",
      "text"
    ],
    [
      "relevant_experience",
      "text"
    ],
    [
      "communication_skill",
      "text"
    ],
    [
      "process",
      "text"
    ],
    [
      "interview_reschedule_date",
      "text"
    ],
    [
      "virtual_onsite",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "reference_details",
      "text"
    ],
    [
      "follow_up_at",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "all_details_sent",
      "text"
    ],
    [
      "submission_date",
      "text"
    ],
    [
      "approval_status",
      "text"
    ],
    [
      "approved_at",
      "text"
    ],
    [
      "approved_by_name",
      "text"
    ],
    [
      "career_gap",
      "text"
    ],
    [
      "recording_filename",
      "text"
    ],
    [
      "resume_filename",
      "text"
    ],
    [
      "documents_availability",
      "text"
    ],
    [
      "relevant_experience_range",
      "text"
    ],
    [
      "relevant_in_hand_range",
      "text"
    ],
    [
      "total_experience",
      "text"
    ],
    [
      "manager_crm",
      "text"
    ],
    [
      "interview_remove_request_id",
      "text"
    ],
    [
      "interview_remove_status",
      "text"
    ],
    [
      "interview_remove_reason",
      "text"
    ],
    [
      "interview_remove_approved_at",
      "text"
    ],
    [
      "submitted_by",
      "text"
    ],
    [
      "data_uploading_date",
      "text"
    ],
    [
      "data_notes",
      "text"
    ],
    [
      "qualification_level",
      "text"
    ],
    [
      "ctc_monthly",
      "text"
    ],
    [
      "recruiter_name",
      "text"
    ],
    [
      "recruiter_designation",
      "text"
    ],
    [
      "interview_availability",
      "text"
    ],
    [
      "approval_requested_at",
      "text"
    ],
    [
      "is_duplicate",
      "text"
    ],
    [
      "follow_up_note",
      "text"
    ],
    [
      "follow_up_status",
      "text"
    ],
    [
      "bucket_assigned_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "experience",
      "text"
    ],
    [
      "source_sr_no",
      "text"
    ],
    [
      "number",
      "text"
    ],
    [
      "profile_priority",
      "text"
    ],
    [
      "last_dialed_at",
      "text"
    ],
    [
      "last_dialed_by_name",
      "text"
    ],
    [
      "dial_attempt_count",
      "text"
    ],
    [
      "last_viewed_at",
      "text"
    ],
    [
      "last_viewed_by_name",
      "text"
    ],
    [
      "duplicate_main_choice",
      "text"
    ],
    [
      "duplicate_main_marked_at",
      "text"
    ],
    [
      "duplicate_main_marked_by",
      "text"
    ],
    [
      "deleted_at",
      "text"
    ],
    [
      "deleted_by",
      "text"
    ],
    [
      "client",
      "text"
    ],
    [
      "jd_id",
      "text"
    ],
    [
      "interview_date",
      "text"
    ],
    [
      "created_by_user_id",
      "text"
    ],
    [
      "created_by_name",
      "text"
    ],
    [
      "recruiter_user_id",
      "text"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "lead_source",
      "text"
    ],
    [
      "hot_lead_status",
      "text"
    ],
    [
      "profile_status",
      "text"
    ],
    [
      "jd_name",
      "text"
    ],
    [
      "jd_notes",
      "text"
    ],
    [
      "employee_code",
      "text"
    ],
    [
      "employee_no",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "employee_file_url",
      "text"
    ],
    [
      "employee_row_no",
      "text"
    ],
    [
      "last_updated_at",
      "text"
    ],
    [
      "note",
      "text"
    ],
    [
      "last_note",
      "text"
    ],
    [
      "last_notes",
      "text"
    ]
  ],
  "tasks": [
    [
      "task_id",
      "text primary key"
    ],
    [
      "title",
      "text"
    ],
    [
      "description",
      "text"
    ],
    [
      "assigned_to_user_id",
      "text"
    ],
    [
      "assigned_to_name",
      "text"
    ],
    [
      "assigned_to_code",
      "text"
    ],
    [
      "assigned_by_user_id",
      "text"
    ],
    [
      "assigned_by_name",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "priority",
      "text"
    ],
    [
      "due_date",
      "text"
    ],
    [
      "due_at",
      "text"
    ],
    [
      "reminder_at",
      "text"
    ],
    [
      "recurring_enabled",
      "text"
    ],
    [
      "recurring_type",
      "text"
    ],
    [
      "recurring_interval_minutes",
      "text"
    ],
    [
      "recurring_parent_task_id",
      "text"
    ],
    [
      "recurring_source_task_id",
      "text"
    ],
    [
      "closed_at",
      "text"
    ],
    [
      "closed_by_user_id",
      "text"
    ],
    [
      "closed_by_name",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "notifications": [
    [
      "notification_id",
      "text primary key"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "title",
      "text"
    ],
    [
      "message",
      "text"
    ],
    [
      "category",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "metadata",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "jd_master": [
    [
      "jd_id",
      "text primary key"
    ],
    [
      "job_title",
      "text"
    ],
    [
      "company",
      "text"
    ],
    [
      "location",
      "text"
    ],
    [
      "preferred_location_rule",
      "text"
    ],
    [
      "qualification_rule",
      "text"
    ],
    [
      "communication_rule",
      "text"
    ],
    [
      "career_gap_rule",
      "text"
    ],
    [
      "documents_rule",
      "text"
    ],
    [
      "all_details_sent_rule",
      "text"
    ],
    [
      "relevant_experience_rule",
      "text"
    ],
    [
      "relevant_salary_rule",
      "text"
    ],
    [
      "process_name",
      "text"
    ],
    [
      "experience",
      "text"
    ],
    [
      "salary",
      "text"
    ],
    [
      "salary_min",
      "text"
    ],
    [
      "salary_max",
      "text"
    ],
    [
      "exp_min",
      "text"
    ],
    [
      "exp_max",
      "text"
    ],
    [
      "pdf_url",
      "text"
    ],
    [
      "jd_status",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "message_template",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "instruction_points",
      "text"
    ],
    [
      "send_items",
      "text"
    ]
  ],
  "notes": [
    [
      "id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "note_type",
      "text"
    ],
    [
      "body",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "parent_note_id",
      "text"
    ],
    [
      "reply_to_note_id",
      "text"
    ],
    [
      "reply_to_username",
      "text"
    ]
  ],
  "interviews": [
    [
      "interview_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "jd_id",
      "text"
    ],
    [
      "stage",
      "text"
    ],
    [
      "scheduled_at",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "submissions": [
    [
      "submission_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "jd_id",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "approval_status",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "submitted_at",
      "text"
    ],
    [
      "approval_requested_at",
      "text"
    ],
    [
      "approved_at",
      "text"
    ],
    [
      "approved_by_name",
      "text"
    ],
    [
      "decision_note",
      "text"
    ],
    [
      "reminder_note",
      "text"
    ],
    [
      "reminder_snoozed_until",
      "text"
    ],
    [
      "next_follow_up_at",
      "text"
    ],
    [
      "approval_rescheduled_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "submitted_by_user_id",
      "text"
    ],
    [
      "submitted_by_name",
      "text"
    ],
    [
      "submitted_by_recruiter_code",
      "text"
    ],
    [
      "submission_comms",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "effective_submission_at",
      "text"
    ],
    [
      "submission_origin_at",
      "text"
    ]
  ],
  "active_sessions": [
    [
      "username",
      "text primary key"
    ],
    [
      "session_token",
      "text"
    ],
    [
      "ip_address",
      "text"
    ],
    [
      "user_agent",
      "text"
    ],
    [
      "device_id",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "last_seen_at",
      "text"
    ],
    [
      "login_at",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "revoked_at",
      "text"
    ],
    [
      "logout_at",
      "text"
    ]
  ],
  "presence": [
    [
      "user_id",
      "text primary key"
    ],
    [
      "last_seen_at",
      "text"
    ],
    [
      "last_page",
      "text"
    ],
    [
      "is_on_break",
      "text"
    ],
    [
      "break_reason",
      "text"
    ],
    [
      "break_started_at",
      "text"
    ],
    [
      "break_expected_end_at",
      "text"
    ],
    [
      "total_break_minutes",
      "text"
    ],
    [
      "locked",
      "text"
    ],
    [
      "last_call_dial_at",
      "text"
    ],
    [
      "last_call_candidate_id",
      "text"
    ],
    [
      "last_call_alert_sent_at",
      "text"
    ],
    [
      "meeting_joined",
      "text"
    ],
    [
      "meeting_joined_at",
      "text"
    ],
    [
      "screen_sharing",
      "text"
    ],
    [
      "screen_frame_url",
      "text"
    ],
    [
      "last_screen_frame_at",
      "text"
    ],
    [
      "work_started_at",
      "text"
    ],
    [
      "total_work_minutes",
      "text"
    ],
    [
      "lock_reason",
      "text"
    ],
    [
      "lock_message",
      "text"
    ],
    [
      "unlock_grace_until",
      "text"
    ],
    [
      "last_activity_at",
      "text"
    ],
    [
      "last_activity_source",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "work_date",
      "text"
    ]
  ],
  "unlock_requests": [
    [
      "request_id",
      "text primary key"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "full_name",
      "text"
    ],
    [
      "reason",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "auto_created",
      "text"
    ],
    [
      "approved_by_user_id",
      "text"
    ],
    [
      "approved_by_name",
      "text"
    ],
    [
      "approved_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "requested_at",
      "text"
    ]
  ],
  "activity_log": [
    [
      "id",
      "text primary key"
    ],
    [
      "activity_id",
      "text"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "action_type",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "metadata",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "activity_type",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ]
  ],
  "scheduled_reports": [
    [
      "report_id",
      "text primary key"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "title",
      "text"
    ],
    [
      "report_type",
      "text"
    ],
    [
      "filters_json",
      "text"
    ],
    [
      "file_format",
      "text"
    ],
    [
      "frequency_minutes",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "next_run_at",
      "text"
    ],
    [
      "last_run_at",
      "text"
    ],
    [
      "last_file_name",
      "text"
    ],
    [
      "period_key",
      "text"
    ],
    [
      "snapshot_json",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "archive_reason",
      "text"
    ],
    [
      "archived_at",
      "text"
    ]
  ],
  "interview_remove_requests": [
    [
      "request_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "reason",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "requested_by_user_id",
      "text"
    ],
    [
      "requested_by_name",
      "text"
    ],
    [
      "approved_by_user_id",
      "text"
    ],
    [
      "approved_by_name",
      "text"
    ],
    [
      "approved_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "suggested_videos": [
    [
      "suggestion_id",
      "text primary key"
    ],
    [
      "suggested_by_user_id",
      "text"
    ],
    [
      "suggested_by_name",
      "text"
    ],
    [
      "category",
      "text"
    ],
    [
      "title",
      "text"
    ],
    [
      "url",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "rejection_reason",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "approved_at",
      "text"
    ],
    [
      "approved_by_name",
      "text"
    ]
  ],
  "goal_post_targets": [
    [
      "goal_post_id",
      "text primary key"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "date",
      "text"
    ],
    [
      "submission_target",
      "text"
    ],
    [
      "submission_done",
      "text"
    ],
    [
      "interview_target",
      "text"
    ],
    [
      "interview_done",
      "text"
    ],
    [
      "selection_target",
      "text"
    ],
    [
      "selection_done",
      "text"
    ],
    [
      "joining_target",
      "text"
    ],
    [
      "joining_done",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "updated_by_user_id",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "employee_daily_stats": [
    [
      "stat_id",
      "text primary key"
    ],
    [
      "stat_date",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "recruiter_name",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "calls_count",
      "text"
    ],
    [
      "connected_calls_count",
      "text"
    ],
    [
      "not_connected_calls_count",
      "text"
    ],
    [
      "incoming_calls_count",
      "text"
    ],
    [
      "outgoing_calls_count",
      "text"
    ],
    [
      "missed_calls_count",
      "text"
    ],
    [
      "talktime_seconds",
      "text"
    ],
    [
      "whatsapp_count",
      "text"
    ],
    [
      "jd_sent_count",
      "text"
    ],
    [
      "submissions_count",
      "text"
    ],
    [
      "interviews_count",
      "text"
    ],
    [
      "selections_count",
      "text"
    ],
    [
      "joinings_count",
      "text"
    ],
    [
      "employee_cut_suspect_count",
      "text"
    ],
    [
      "short_ring_count",
      "text"
    ],
    [
      "candidate_no_answer_likely_count",
      "text"
    ],
    [
      "suspicious_call_score",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "dialed_calls_count",
      "text"
    ],
    [
      "avg_talktime_seconds",
      "text"
    ],
    [
      "missing_call_log_count",
      "text"
    ],
    [
      "recording_missing_count",
      "text"
    ],
    [
      "callback_pending_count",
      "text"
    ],
    [
      "unique_called_profiles_count",
      "text"
    ],
    [
      "repeated_calls_count",
      "text"
    ],
    [
      "manual_app_dial_count",
      "text"
    ],
    [
      "app_open_count",
      "text"
    ],
    [
      "last_location_at",
      "text"
    ]
  ],
  "mobile_devices": [
    [
      "device_id",
      "text primary key"
    ],
    [
      "pairing_code",
      "text"
    ],
    [
      "device_token",
      "text"
    ],
    [
      "user_id",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "role",
      "text"
    ],
    [
      "device_name",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "paired_at",
      "text"
    ],
    [
      "last_seen_at",
      "text"
    ],
    [
      "expires_at",
      "text"
    ],
    [
      "logout_reason",
      "text"
    ],
    [
      "revoked_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "last_latitude",
      "text"
    ],
    [
      "last_longitude",
      "text"
    ],
    [
      "last_location_accuracy_meters",
      "text"
    ],
    [
      "last_location_at",
      "text"
    ],
    [
      "last_location_source",
      "text"
    ]
  ],
  "dialer_sessions": [
    [
      "session_id",
      "text primary key"
    ],
    [
      "owner_user_id",
      "text"
    ],
    [
      "owner_username",
      "text"
    ],
    [
      "assigned_user_id",
      "text"
    ],
    [
      "assigned_username",
      "text"
    ],
    [
      "device_id",
      "text"
    ],
    [
      "device_token",
      "text"
    ],
    [
      "section",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "next_call_gap_seconds",
      "text"
    ],
    [
      "total_items",
      "text"
    ],
    [
      "completed_items",
      "text"
    ],
    [
      "current_queue_item_id",
      "text"
    ],
    [
      "current_candidate_id",
      "text"
    ],
    [
      "current_candidate_name",
      "text"
    ],
    [
      "current_phone",
      "text"
    ],
    [
      "live_status",
      "text"
    ],
    [
      "mobile_auto_start",
      "text"
    ],
    [
      "mobile_command",
      "text"
    ],
    [
      "command_type",
      "text"
    ],
    [
      "command_version",
      "text"
    ],
    [
      "start_from_crm",
      "text"
    ],
    [
      "call_source",
      "text"
    ],
    [
      "manual_number",
      "text"
    ],
    [
      "client_queue_id",
      "text"
    ],
    [
      "client_queue_signature",
      "text"
    ],
    [
      "crm_open_profile_candidate_id",
      "text"
    ],
    [
      "crm_open_profile_queue_item_id",
      "text"
    ],
    [
      "crm_open_profile_request_version",
      "text"
    ],
    [
      "crm_open_profile_requested_at",
      "text"
    ],
    [
      "crm_open_profile_source",
      "text"
    ],
    [
      "next_queue_item_id",
      "text"
    ],
    [
      "next_candidate_id",
      "text"
    ],
    [
      "next_candidate_name",
      "text"
    ],
    [
      "next_phone",
      "text"
    ],
    [
      "warm_profile_candidate_ids",
      "text"
    ],
    [
      "started_at",
      "text"
    ],
    [
      "stopped_at",
      "text"
    ],
    [
      "paused_at",
      "text"
    ],
    [
      "paused_by",
      "text"
    ],
    [
      "resumed_at",
      "text"
    ],
    [
      "resumed_by",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "source_mode",
      "text"
    ],
    [
      "manual_entry_source",
      "text"
    ],
    [
      "checked_count",
      "text"
    ],
    [
      "no_checked_profiles_blocked",
      "text"
    ]
  ],
  "dialer_queue_items": [
    [
      "queue_item_id",
      "text primary key"
    ],
    [
      "session_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "process",
      "text"
    ],
    [
      "location",
      "text"
    ],
    [
      "qualification",
      "text"
    ],
    [
      "section",
      "text"
    ],
    [
      "profile_section",
      "text"
    ],
    [
      "queue_order",
      "text"
    ],
    [
      "dialer_sequence",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "profile_number",
      "text"
    ],
    [
      "imn_candidate_id",
      "text"
    ],
    [
      "last_note",
      "text"
    ],
    [
      "interview_date",
      "text"
    ],
    [
      "call_enabled",
      "text"
    ],
    [
      "enabled",
      "text"
    ],
    [
      "selected",
      "text"
    ],
    [
      "is_callable",
      "text"
    ],
    [
      "skip_reason",
      "text"
    ],
    [
      "skipped_by",
      "text"
    ],
    [
      "skipped_at",
      "text"
    ],
    [
      "client_queue_id",
      "text"
    ],
    [
      "call_source",
      "text"
    ],
    [
      "source_mode",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "started_at",
      "text"
    ],
    [
      "ended_at",
      "text"
    ],
    [
      "last_call_log_id",
      "text"
    ],
    [
      "client",
      "text"
    ],
    [
      "role",
      "text"
    ],
    [
      "experience",
      "text"
    ],
    [
      "source",
      "text"
    ],
    [
      "manual_entry_source",
      "text"
    ],
    [
      "recruiter_name",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "profile_status",
      "text"
    ],
    [
      "jd_name",
      "text"
    ],
    [
      "source_row_index",
      "text"
    ],
    [
      "source_profile_key",
      "text"
    ],
    [
      "call_order",
      "integer"
    ],
    [
      "original_row_index",
      "integer"
    ]
  ],
  "manual_dialer_calls": [
    [
      "manual_call_id",
      "text primary key"
    ],
    [
      "session_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "employee_username",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "note",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "queue_item_id",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "device_id",
      "text"
    ],
    [
      "device_token",
      "text"
    ],
    [
      "call_log_id",
      "text"
    ],
    [
      "call_source",
      "text"
    ],
    [
      "source_mode",
      "text"
    ],
    [
      "command_source",
      "text"
    ],
    [
      "manual_entry_source",
      "text"
    ],
    [
      "synced_from_mobile_app",
      "text"
    ]
  ],
  "call_logs": [
    [
      "call_log_id",
      "text primary key"
    ],
    [
      "session_id",
      "text"
    ],
    [
      "queue_item_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "employee_username",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "direction",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "call_started_at",
      "text"
    ],
    [
      "call_ended_at",
      "text"
    ],
    [
      "answered_at",
      "text"
    ],
    [
      "duration_seconds",
      "text"
    ],
    [
      "talktime_seconds",
      "text"
    ],
    [
      "ring_seconds",
      "text"
    ],
    [
      "idle_seconds",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "call_source",
      "text"
    ],
    [
      "source_mode",
      "text"
    ],
    [
      "recording_status",
      "text"
    ],
    [
      "recording_url",
      "text"
    ],
    [
      "recording_file_id",
      "text"
    ],
    [
      "synced_from",
      "text"
    ],
    [
      "stats_counted",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "dial_hold_seconds",
      "text"
    ],
    [
      "call_quality",
      "text"
    ],
    [
      "disconnect_by",
      "text"
    ],
    [
      "disconnect_actor_guess",
      "text"
    ],
    [
      "employee_cut_suspect",
      "text"
    ],
    [
      "early_cut_flag",
      "text"
    ],
    [
      "early_cut_reason",
      "text"
    ],
    [
      "suspicious_score",
      "text"
    ],
    [
      "call_log_available",
      "text"
    ],
    [
      "qa_checked_at",
      "text"
    ],
    [
      "callback_status",
      "text"
    ],
    [
      "callback_done_at",
      "text"
    ],
    [
      "callback_by_user_id",
      "text"
    ],
    [
      "callback_by_name",
      "text"
    ],
    [
      "callback_call_log_id",
      "text"
    ],
    [
      "username",
      "text"
    ],
    [
      "current_queue_item_id",
      "text"
    ],
    [
      "current_candidate_id",
      "text"
    ],
    [
      "note",
      "text"
    ],
    [
      "call_note",
      "text"
    ],
    [
      "dialed_calls_count",
      "text"
    ],
    [
      "employee_early_cut_suspect",
      "text"
    ],
    [
      "candidate_no_answer_likely",
      "text"
    ],
    [
      "phone_log_sync_id",
      "text"
    ],
    [
      "android_call_type",
      "text"
    ],
    [
      "manual_entry_source",
      "text"
    ],
    [
      "crm_click_source",
      "text"
    ],
    [
      "mobile_manual_dialer",
      "text"
    ],
    [
      "crm_tracked_number",
      "text"
    ],
    [
      "counting_rule_version",
      "text"
    ],
    [
      "duplicate_guard_key",
      "text"
    ],
    [
      "employee_latitude",
      "text"
    ],
    [
      "employee_longitude",
      "text"
    ],
    [
      "employee_location_accuracy_meters",
      "text"
    ],
    [
      "employee_location_captured_at",
      "text"
    ],
    [
      "employee_location_source",
      "text"
    ],
    [
      "client",
      "text"
    ],
    [
      "process",
      "text"
    ],
    [
      "role",
      "text"
    ],
    [
      "location",
      "text"
    ],
    [
      "source",
      "text"
    ],
    [
      "profile_number",
      "text"
    ],
    [
      "imn_candidate_id",
      "text"
    ],
    [
      "recruiter_name",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "profile_status",
      "text"
    ],
    [
      "jd_name",
      "text"
    ],
    [
      "source_profile_key",
      "text"
    ]
  ],
  "call_quality_events": [
    [
      "event_id",
      "text primary key"
    ],
    [
      "call_log_id",
      "text"
    ],
    [
      "session_id",
      "text"
    ],
    [
      "queue_item_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "employee_username",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "call_started_at",
      "text"
    ],
    [
      "call_ended_at",
      "text"
    ],
    [
      "ring_seconds",
      "text"
    ],
    [
      "dial_hold_seconds",
      "text"
    ],
    [
      "duration_seconds",
      "text"
    ],
    [
      "talktime_seconds",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "disconnect_by",
      "text"
    ],
    [
      "employee_cut_suspect",
      "text"
    ],
    [
      "early_cut_flag",
      "text"
    ],
    [
      "early_cut_reason",
      "text"
    ],
    [
      "suspicious_score",
      "text"
    ],
    [
      "evidence_source",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "employee_early_cut_suspect",
      "text"
    ],
    [
      "candidate_no_answer_likely",
      "text"
    ]
  ],
  "recording_files": [
    [
      "recording_file_id",
      "text primary key"
    ],
    [
      "call_log_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "storage_bucket",
      "text"
    ],
    [
      "storage_path",
      "text"
    ],
    [
      "recording_url",
      "text"
    ],
    [
      "original_filename",
      "text"
    ],
    [
      "compressed_size_bytes",
      "text"
    ],
    [
      "duration_seconds",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "uploaded_at",
      "text"
    ],
    [
      "created_at",
      "text"
    ]
  ],
  "live_call_state": [
    [
      "state_id",
      "text primary key"
    ],
    [
      "session_id",
      "text"
    ],
    [
      "queue_item_id",
      "text"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "candidate_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "employee_username",
      "text"
    ],
    [
      "live_status",
      "text"
    ],
    [
      "command_version",
      "text"
    ],
    [
      "call_source",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "employee_locations": [
    [
      "location_id",
      "text primary key"
    ],
    [
      "device_id",
      "text"
    ],
    [
      "device_token",
      "text"
    ],
    [
      "employee_user_id",
      "text"
    ],
    [
      "employee_username",
      "text"
    ],
    [
      "employee_name",
      "text"
    ],
    [
      "latitude",
      "text"
    ],
    [
      "longitude",
      "text"
    ],
    [
      "accuracy_meters",
      "text"
    ],
    [
      "provider",
      "text"
    ],
    [
      "captured_at",
      "text"
    ],
    [
      "sync_mode",
      "text"
    ],
    [
      "app_version",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "settings": [
    [
      "setting_key",
      "text primary key"
    ],
    [
      "setting_value",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "Instructions",
      "text"
    ],
    [
      "deleted_at",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "app_settings": [
    [
      "key",
      "text primary key"
    ],
    [
      "value",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "candidate_jd_feedback": [
    ["feedback_id", "text primary key"],
    ["jd_id", "text"],
    ["candidate_id", "text"],
    ["feedback_status", "text"],
    ["feedback_note", "text"],
    ["username", "text"],
    ["user_id", "text"],
    ["updated_at", "text"],
    ["created_at", "text"]
  ],
  "candidate_reset_archive": [
    [
      "archive_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "source_table",
      "text"
    ],
    [
      "source_row_json",
      "text"
    ],
    [
      "reset_at",
      "text"
    ],
    [
      "reset_by_user_id",
      "text"
    ],
    [
      "reset_by_name",
      "text"
    ]
  ],
  "candidate_files": [
    [
      "file_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "file_kind",
      "text"
    ],
    [
      "original_name",
      "text"
    ],
    [
      "storage_name",
      "text"
    ],
    [
      "mime_type",
      "text"
    ],
    [
      "size_bytes",
      "text"
    ],
    [
      "content_base64",
      "text"
    ],
    [
      "uploaded_by_user_id",
      "text"
    ],
    [
      "uploaded_by_name",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "source",
      "text"
    ],
    [
      "suggested_file_name",
      "text"
    ],
    [
      "updated_at",
      "text"
    ]
  ],
  "revenue_hub_entries": [
    [
      "revenue_id",
      "text primary key"
    ],
    [
      "candidate_id",
      "text"
    ],
    [
      "full_name",
      "text"
    ],
    [
      "phone",
      "text"
    ],
    [
      "process",
      "text"
    ],
    [
      "client_name",
      "text"
    ],
    [
      "location",
      "text"
    ],
    [
      "qualification",
      "text"
    ],
    [
      "recruiter_name",
      "text"
    ],
    [
      "recruiter_code",
      "text"
    ],
    [
      "interview_date",
      "text"
    ],
    [
      "selection_date",
      "text"
    ],
    [
      "joining_date",
      "text"
    ],
    [
      "joined_date",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "payout_status",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "created_by_user_id",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "communication_skill",
      "text"
    ],
    [
      "experience_range",
      "text"
    ],
    [
      "salary_range",
      "text"
    ],
    [
      "submission_date",
      "text"
    ],
    [
      "interview_datetime",
      "text"
    ],
    [
      "interview_mode",
      "text"
    ],
    [
      "payout_amount",
      "text"
    ],
    [
      "resume_filename",
      "text"
    ],
    [
      "recording_filename",
      "text"
    ],
    [
      "deleted_at",
      "text"
    ],
    [
      "deleted_by_name",
      "text"
    ],
    [
      "deleted_by_user_id",
      "text"
    ]
  ],
  "client_pipeline": [
    [
      "lead_id",
      "text primary key"
    ],
    [
      "client_name",
      "text"
    ],
    [
      "contact_person",
      "text"
    ],
    [
      "contact_phone",
      "text"
    ],
    [
      "city",
      "text"
    ],
    [
      "industry",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "owner_username",
      "text"
    ],
    [
      "priority",
      "text"
    ],
    [
      "openings_count",
      "text"
    ],
    [
      "last_follow_up_at",
      "text"
    ],
    [
      "next_follow_up_at",
      "text"
    ],
    [
      "notes",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "contact_email",
      "text"
    ],
    [
      "visible_to_tl_user_ids",
      "text"
    ],
    [
      "visible_to_tl_codes",
      "text"
    ],
    [
      "visible_to_tl_names",
      "text"
    ]
  ],
  "revenue_entries": [
    [
      "revenue_id",
      "text primary key"
    ]
  ],
  "hot_leads": [
    [
      "lead_id",
      "text primary key"
    ]
  ],
  "chat_groups": [
    ["group_id", "text primary key"],
    ["title", "text"],
    ["created_by", "text"],
    ["created_by_username", "text"],
    ["status", "text"],
    ["visibility", "text"],
    ["created_at", "text"],
    ["updated_at", "text"],
    ["deleted_by_username", "text"],
    ["deleted_at", "text"]
  ],
  "chat_group_members": [
    ["id", "bigint primary key"],
    ["group_id", "text"],
    ["user_id", "text"],
    ["username", "text"],
    ["full_name", "text"],
    ["role", "text"],
    ["added_by_username", "text"],
    ["created_at", "text"],
    ["updated_at", "text"],
    ["status", "text"],
    ["removed_at", "text"],
    ["deleted_at", "text"],
    ["removed_by_username", "text"]
  ],
  "messages": [
    [
      "id",
      "bigserial primary key"
    ],
    [
      "sender_username",
      "text"
    ],
    [
      "sender_name",
      "text"
    ],
    [
      "sender_role",
      "text"
    ],
    [
      "recipient_username",
      "text"
    ],
    [
      "body",
      "text"
    ],
    [
      "original_body",
      "text"
    ],
    [
      "message",
      "text"
    ],
    [
      "message_text",
      "text"
    ],
    [
      "content",
      "text"
    ],
    [
      "created_at",
      "text"
    ],
    [
      "updated_at",
      "text"
    ],
    [
      "thread_key",
      "text"
    ],
    [
      "thread_type",
      "text"
    ],
    [
      "chat_type",
      "text"
    ],
    [
      "reference_type",
      "text"
    ],
    [
      "reference_id",
      "text"
    ],
    [
      "mention_usernames",
      "text"
    ],
    [
      "delete_mode",
      "text"
    ],
    [
      "deleted_by_username",
      "text"
    ],
    [
      "deleted_at",
      "text"
    ],
    [
      "status",
      "text"
    ],
    [
      "moderation_status",
      "text"
    ],
    [
      "moderation_reason",
      "text"
    ],
    [
      "moderation_word",
      "text"
    ],
    [
      "reviewed_by_username",
      "text"
    ],
    [
      "reviewed_at",
      "text"
    ],
    [
      "review_decision_note",
      "text"
    ],
    [
      "created_by_username",
      "text"
    ],
    [
      "created_by_name",
      "text"
    ],
    [
      "created_by_role",
      "text"
    ]
  ]
};

const LOGIN_DEFAULTS = [
  { user_id: 'MGR-001', username: 'Aaryansh', password_hash: 'pbkdf2:sha256:150000$8EgUEg7Q8xYo8BqMw50ziQ$4j1V7KmKu_-DYuR4jBj8dkPo6luH1bMnsFOzu4oR6I8', full_name: 'Aaryansh Patel', designation: 'Manager', role: 'manager', recruiter_code: 'MGR001', tl_user_id: null, tl_code: null, tl_name: null },
  { user_id: 'TL-001', username: 'Kunal', password_hash: 'pbkdf2:sha256:150000$yBCC9s3r7fBkBrBTiuNI3g$xm0S4c-KfoH3p_b3Z6ZMKUm9bihGyiJ5t8C6jiwArsY', full_name: 'Kunal Sharma', designation: 'Team Lead', role: 'tl', recruiter_code: 'TL001', tl_user_id: null, tl_code: null, tl_name: null },
  { user_id: 'TL-002', username: 'Pratham', password_hash: 'pbkdf2:sha256:150000$m8_d9H9IJ-OMQrVQIj6Dww$xGjAfifoHKtengzJUw0Z6GV4bFp7AiL3pOoZH29QHmQ', full_name: 'Pratham Gupta', designation: 'Team Lead', role: 'tl', recruiter_code: 'TL002', tl_user_id: null, tl_code: null, tl_name: null },
  { user_id: 'REC-001', username: 'Anshika', password_hash: 'pbkdf2:sha256:150000$8GE0Kxs_ptVj-HwUQdturg$ntXZhNlykTyno1Z_44k2eYEtWeNJcNHG4ISds-t-afI', full_name: 'Anshika Tiwari', designation: 'Recruiter', role: 'recruiter', recruiter_code: 'REC001', tl_user_id: 'TL-001', tl_code: 'TL001', tl_name: 'Kunal Sharma' },
  { user_id: 'REC-002', username: 'Aayushi', password_hash: 'pbkdf2:sha256:150000$nDqoP-6TtyGH4ja96QYaTw$Ci0BWwrZpIQUW9zrRpevBDE3SH1XyR3UkyrS4B11kT0', full_name: 'Aayushi Sharma', designation: 'Recruiter', role: 'recruiter', recruiter_code: 'REC002', tl_user_id: 'TL-001', tl_code: 'TL001', tl_name: 'Kunal Sharma' },
  { user_id: 'REC-003', username: 'Sakshi', password_hash: 'pbkdf2:sha256:150000$En8DmxOQSD5n8gzQhbBvow$aHwfRA4kCMH1XLvZNDVy-m-e9r_ZiNYTxPsay62kwII', full_name: 'Sakshi Pandya', designation: 'Recruiter', role: 'recruiter', recruiter_code: 'REC003', tl_user_id: 'TL-002', tl_code: 'TL002', tl_name: 'Pratham Gupta' },
  { user_id: 'REC-004', username: 'Hajera', password_hash: 'pbkdf2:sha256:150000$f-ICommAnYE7l6guBzf3dQ$SVIWOtsrI6rXgLQLXVmiue7Li2qVTt0X9vukcXKKlQ0', full_name: 'Hajera Nawab', designation: 'Recruiter', role: 'recruiter', recruiter_code: 'REC004', tl_user_id: 'TL-002', tl_code: 'TL002', tl_name: 'Pratham Gupta' },
];

function ident(value) { return `"${String(value).replace(/"/g, '""')}"`; }

async function ensureTable(table, columns) {
  if (!columns?.length) return;
  const createCols = columns.map(([name, type]) => `${ident(name)} ${type}`).join(', ');
  await store.query(`create table if not exists public.${ident(table)} (${createCols})`);
  for (const [name, type] of columns) {
    // ADD COLUMN cannot repeat PRIMARY KEY safely; existing/missing tables already receive it via CREATE.
    const additiveType = String(type).replace(/\s+primary\s+key\b/ig, '').trim() || 'text';
    await store.query(`alter table public.${ident(table)} add column if not exists ${ident(name)} ${additiveType}`);
  }
}

async function ensureConfiguredUserRows() {
  for (const item of LOGIN_DEFAULTS) {
    await store.query(`insert into public.users
      (user_id, username, password, full_name, designation, role, recruiter_code, tl_user_id, tl_code, tl_name, is_active, theme_name, email, created_at, updated_at)
      select $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'true','orange','',now()::text,now()::text
      where not exists (select 1 from public.users where user_id = $1)`,
      [item.user_id, item.username, item.password_hash, item.full_name, item.designation, item.role, item.recruiter_code, item.tl_user_id, item.tl_code, item.tl_name]);
  }
}

async function ensureBasicSettings() {
  const settings = [
    ['basic_crm_mode','true','Intern Basic CRM mode','Only core intern workflow slices are enabled.'],
    ['calling_assistant_pair_code_digits','4','Calling Assistant compatibility','Keep at 4 for the packaged Calling Assistant.'],
  ];
  for (const row of settings) {
    await store.query(`insert into public.settings (setting_key,setting_value,notes,"Instructions",status,updated_at)
      select $1,$2,$3,$4,'Active',now()::text where not exists (select 1 from public.settings where setting_key=$1)`, row);
  }
  await store.query(`insert into public.app_settings (key,value,updated_at)
    select 'calling_assistant_pair_code_digits','4',now()::text where not exists (select 1 from public.app_settings where key='calling_assistant_pair_code_digits')`);
}

async function basicSchemaHealth() {
  if (mode !== 'postgres' || !store.pool) return { ok: true, mode, tables: [], missing_tables: [], missing_columns: [] };
  const expected = BASIC_TABLE_SPECS;
  const tableRows = await store.query(`select table_name from information_schema.tables where table_schema='public'`);
  const columnRows = await store.query(`select table_name,column_name from information_schema.columns where table_schema='public'`);
  const presentTables = new Set(tableRows.map((r) => String(r.table_name)));
  const byTable = new Map();
  for (const row of columnRows) {
    const key=String(row.table_name); if(!byTable.has(key)) byTable.set(key,new Set()); byTable.get(key).add(String(row.column_name));
  }
  const missingTables=[]; const missingColumns=[];
  for (const [table, cols] of Object.entries(expected)) {
    if (!presentTables.has(table)) missingTables.push(table);
    const have=byTable.get(table)||new Set();
    for (const [col] of cols) if(!have.has(col)) missingColumns.push(`${table}.${col}`);
  }
  return { ok: !missingTables.length && !missingColumns.length, mode, tables: Object.keys(expected), missing_tables: missingTables, missing_columns: missingColumns };
}

async function ensureBasicSchema() {
  if (mode !== 'postgres' || !store.pool) return { ok: true, skipped: true, mode };
  await store.query('select 1 as ok');
  for (const [table, columns] of Object.entries(BASIC_TABLE_SPECS)) await ensureTable(table, columns);
  // Legacy activity_log schema used id as PK while code writes activity_id. Make inserts reliable.
  await store.query(`alter table public.activity_log alter column id set default md5(random()::text || clock_timestamp()::text)`);
  await store.query(`create index if not exists basic_users_username_ci_idx on public.users ((lower(username))) where username is not null`);
  await store.query(`create index if not exists basic_candidates_recruiter_updated on public.candidates (recruiter_code, updated_at desc)`);
  await store.query(`create index if not exists basic_submissions_candidate_time on public.submissions (candidate_id, submitted_at desc)`);
  await store.query(`create index if not exists basic_activity_user_time on public.activity_log (username, created_at desc)`);
  await store.query(`create index if not exists basic_notes_candidate_created on public.notes (candidate_id, created_at desc)`);
  await store.query(`create index if not exists basic_notifications_user_status_time on public.notifications (user_id, status, created_at desc)`);
  await store.query(`create index if not exists basic_chat_messages_thread_id on public.messages (thread_key, id desc)`);
  await store.query(`create index if not exists basic_chat_group_members_group_user on public.chat_group_members (group_id, user_id)`);
  await store.query(`create index if not exists basic_tasks_due_date on public.tasks (due_date) where coalesce(due_date,'') <> ''`);
  await store.query(`create index if not exists basic_tasks_due_at on public.tasks (due_at) where coalesce(due_at,'') <> ''`);
  await store.query(`create index if not exists basic_tasks_reminder_at on public.tasks (reminder_at) where coalesce(reminder_at,'') <> ''`);
  await store.query(`create index if not exists basic_interviews_scheduled on public.interviews (scheduled_at) where coalesce(scheduled_at,'') <> ''`);
  await store.query(`create index if not exists basic_candidates_followup on public.candidates (follow_up_at) where coalesce(follow_up_at,'') <> ''`);
  await ensureBasicSettings();
  await ensureConfiguredUserRows();
  return basicSchemaHealth();
}

module.exports = { BASIC_TABLE_SPECS, LOGIN_DEFAULTS, ensureBasicSchema, basicSchemaHealth };
