-- Career Crox Freelancer CRM - LIVE CLEAN RESET
-- This file rebuilds the schema with NO sample candidates, NO sample tasks, NO sample JDs,
-- and NO sample notifications. It only inserts one bootstrap manager login so you can enter the CRM.
--
-- Bootstrap login
-- Username: manager@careercrox.local
-- Password: ChangeMe#2026
-- IMPORTANT: change this password immediately after first login.

drop schema if exists public cascade;
create schema public;

create table public.users (
  user_id text primary key,
  username text unique not null,
  password text not null,
  full_name text,
  designation text,
  role text,
  recruiter_code text,
  assigned_tl_user_id text,
  assigned_tl_name text,
  is_active text default '1',
  theme_name text,
  updated_at text
);

create table public.candidates (
  candidate_id text primary key,
  call_connected text,
  looking_for_job text,
  full_name text,
  phone text,
  location text,
  qualification text,
  recruiter_code text,
  preferred_location text,
  in_hand_salary text,
  relevant_experience text,
  communication_skill text,
  process text,
  interview_reschedule_date text,
  virtual_onsite text,
  notes text,
  reference_details text,
  follow_up_at text,
  status text,
  all_details_sent text,
  submission_date text,
  approval_status text,
  approved_at text,
  approved_by_name text,
  career_gap text,
  recording_filename text,
  resume_filename text,
  documents_availability text,
  relevant_experience_range text,
  relevant_in_hand_range text,
  total_experience text,
  manager_crm text,
  interview_remove_request_id text,
  interview_remove_status text,
  interview_remove_reason text,
  interview_remove_approved_at text,
  submitted_by text,
  data_uploading_date text,
  data_notes text,
  qualification_level text,
  ctc_monthly text,
  recruiter_name text,
  recruiter_designation text,
  interview_availability text,
  approval_requested_at text,
  is_duplicate text,
  follow_up_note text,
  follow_up_status text,
  bucket_assigned_at text,
  created_at text,
  updated_at text,
  experience text,
  source_sr_no text
);

create table public.tasks (
  task_id text primary key,
  title text,
  description text,
  assigned_to_user_id text,
  assigned_to_name text,
  assigned_to_code text,
  assigned_by_user_id text,
  assigned_by_name text,
  status text,
  priority text,
  due_date text,
  recurring_enabled text,
  recurring_type text,
  recurring_interval_minutes text,
  recurring_parent_task_id text,
  recurring_source_task_id text,
  closed_at text,
  closed_by_user_id text,
  closed_by_name text,
  created_at text,
  updated_at text
);

create table public.notifications (
  notification_id text primary key,
  user_id text,
  title text,
  message text,
  category text,
  status text,
  metadata text,
  created_at text
);

create table public.jd_master (
  jd_id text primary key,
  job_title text,
  company text,
  location text,
  preferred_location_rule text,
  qualification_rule text,
  communication_rule text,
  career_gap_rule text,
  documents_rule text,
  all_details_sent_rule text,
  relevant_experience_rule text,
  relevant_salary_rule text,
  process_name text,
  experience text,
  salary text,
  salary_min text,
  salary_max text,
  exp_min text,
  exp_max text,
  pdf_url text,
  jd_status text,
  notes text,
  instruction_points text,
  message_template text,
  send_items text,
  created_at text,
  updated_at text
);

create table public.settings (
  setting_key text primary key,
  setting_value text,
  notes text,
  "Instructions" text
);

create table public.notes (
  id bigint primary key,
  candidate_id text,
  username text,
  note_type text,
  body text,
  created_at text
);

create table public.interview_remove_requests (
  request_id text primary key,
  candidate_id text,
  current_interview_date text,
  reason text,
  status text,
  requested_by_user_id text,
  requested_by_name text,
  approved_by_user_id text,
  approved_by_name text,
  approved_at text,
  requested_at text,
  created_at text
);


create table public.candidate_jd_feedback (
  feedback_id text primary key,
  jd_id text,
  candidate_id text,
  feedback_status text,
  feedback_note text,
  username text,
  user_id text,
  updated_at text,
  created_at text
);

create table public.messages (
  id bigint generated by default as identity primary key,
  sender_username text,
  sender_role text,
  recipient_username text,
  body text,
  original_body text,
  created_at text,
  thread_key text,
  thread_type text,
  reference_type text,
  reference_id text,
  mention_usernames text,
  delete_mode text,
  deleted_by_username text,
  deleted_at text
);

create table public.interviews (
  interview_id text primary key,
  candidate_id text,
  jd_id text,
  stage text,
  scheduled_at text,
  status text,
  created_at text
);

create table public.submissions (
  submission_id text primary key,
  candidate_id text,
  jd_id text,
  recruiter_code text,
  status text,
  approval_status text,
  decision_note text,
  approval_requested_at text,
  approved_by_name text,
  approved_at text,
  approval_rescheduled_at text,
  submitted_at text,
  submitted_by_user_id text,
  submitted_by_name text,
  submitted_by_recruiter_code text,
  next_follow_up_at text,
  reminder_snoozed_until text,
  reminder_note text,
  updated_at text
);

alter table public.submissions add column if not exists submitted_by_user_id text;
alter table public.submissions add column if not exists submitted_by_name text;
alter table public.submissions add column if not exists submitted_by_recruiter_code text;

create table public.active_sessions (
  username text primary key,
  session_token text,
  ip_address text,
  user_agent text,
  updated_at timestamptz default now()
);

create table public.presence (
  user_id text primary key,
  last_seen_at text,
  last_page text,
  is_on_break text,
  break_reason text,
  break_started_at text,
  break_expected_end_at text,
  total_break_minutes text,
  locked text,
  lock_reason text,
  lock_message text,
  unlock_grace_until text,
  last_call_dial_at text,
  last_call_candidate_id text,
  last_call_alert_sent_at text,
  meeting_joined text,
  meeting_joined_at text,
  screen_sharing text,
  screen_frame_url text,
  last_screen_frame_at text,
  work_started_at text,
  total_work_minutes text
);

alter table public.presence add column if not exists lock_reason text;
alter table public.presence add column if not exists lock_message text;
alter table public.presence add column if not exists unlock_grace_until text;

create table public.unlock_requests (
  request_id text primary key,
  user_id text,
  status text,
  reason text,
  requested_at text,
  approved_by_user_id text,
  approved_by_name text,
  approved_at text
);

create table public.activity_log (
  activity_id text primary key,
  user_id text,
  username text,
  action_type text,
  candidate_id text,
  metadata text,
  created_at text
);

create table public.candidate_files (
  file_id text primary key,
  candidate_id text not null,
  file_kind text not null,
  original_name text,
  storage_name text,
  mime_type text,
  size_bytes text,
  content_base64 text,
  uploaded_by_user_id text,
  uploaded_by_name text,
  created_at text
);

create table public.yt_hub_playlists (
  playlist_id text primary key,
  title text,
  description text,
  accent text,
  template_key text,
  created_by_user_id text,
  created_by_name text,
  status text,
  created_at text,
  updated_at text
);

create table public.yt_hub_videos (
  video_id text primary key,
  playlist_id text,
  title text,
  url text,
  thumbnail_url text,
  order_index text,
  created_by_user_id text,
  created_by_name text,
  status text,
  created_at text,
  updated_at text
);

create table public.important_resources (
  resource_id text primary key,
  title text,
  description text,
  resource_type text,
  url text,
  original_name text,
  mime_type text,
  size_bytes text,
  content_base64 text,
  created_by_user_id text,
  created_by_name text,
  status text,
  created_at text,
  updated_at text
);

create table public.scheduled_reports (
  report_id text primary key,
  user_id text,
  title text,
  report_type text,
  filters_json text,
  file_format text,
  frequency_minutes text,
  status text,
  next_run_at text,
  last_run_at text,
  last_file_name text,
  period_key text,
  snapshot_json text,
  created_at text
);

create table public.user_onboarding_requests (
  request_id text primary key,
  user_id text,
  username text,
  full_name text,
  email text,
  recruiter_code text,
  designation text,
  role text,
  status text,
  requested_at text,
  approved_at text,
  approved_by_name text,
  notes text
);

create table public.user_onboarding_documents (
  document_id text primary key,
  request_id text,
  user_id text,
  username text,
  document_type text,
  original_name text,
  mime_type text,
  size_bytes text,
  content_base64 text,
  status text,
  created_at text
);

create table public.password_reset_requests (
  request_id text primary key,
  user_id text,
  username text,
  full_name text,
  email text,
  recruiter_code text,
  status text,
  reason text,
  requested_at text,
  resolved_by_name text,
  resolved_at text
);

create table public.aaria_queue (
  task_id text primary key,
  user_id text,
  serial_hint text,
  command_text text,
  status text,
  result_text text,
  created_at text,
  updated_at text
);

create table public.client_pipeline (
  lead_id text primary key,
  client_name text,
  contact_person text,
  contact_phone text,
  city text,
  industry text,
  status text,
  owner_username text,
  priority text,
  openings_count text,
  last_follow_up_at text,
  next_follow_up_at text,
  notes text,
  created_at text,
  updated_at text
);

create table public.client_requirements (
  req_id text primary key,
  lead_id text,
  jd_title text,
  city text,
  openings text,
  target_ctc text,
  status text,
  assigned_tl text,
  assigned_manager text,
  fill_target_date text,
  created_at text
);


create table public.revenue_entries (
  revenue_id text primary key,
  candidate_id text,
  recruiter_code text,
  recruiter_name text,
  status text,
  notes text,
  created_at text,
  updated_at text
);

create table public.chat_groups (
  group_id text primary key,
  title text,
  theme text,
  created_by text,
  created_at text
);

create table public.chat_group_members (
  id bigint generated by default as identity primary key,
  group_id text,
  user_id text
);

create table public.chat_user_state (
  user_id text primary key,
  selected_group_id text,
  emoji_recent text
);

create table public.learning_progress (
  progress_id text primary key,
  user_id text,
  video_id text,
  section_key text,
  title text,
  url text,
  completed text,
  updated_at text
);

create table public.suggested_videos (
  suggestion_id text primary key,
  suggested_by_user_id text,
  suggested_by_name text,
  category text,
  title text,
  url text,
  status text,
  rejection_reason text,
  created_at text,
  approved_at text,
  approved_by_name text
);


-- Revenue Hub workflow table
create table if not exists public.revenue_hub_entries (
  revenue_id text primary key,
  candidate_id text not null,
  full_name text default '',
  phone text default '',
  process text default '',
  client_name text default '',
  location text default '',
  qualification text default '',
  recruiter_name text default '',
  recruiter_code text default '',
  interview_date date,
  selection_date date,
  joining_date date,
  joined_date date,
  status text default 'will_come_for_interview',
  payout_status text default 'none',
  notes text default '',
  created_by_user_id text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_revenue_hub_candidate on public.revenue_hub_entries(candidate_id);
create index if not exists idx_revenue_hub_status on public.revenue_hub_entries(status);
create index if not exists idx_revenue_hub_payout on public.revenue_hub_entries(payout_status);
create index if not exists idx_revenue_hub_recruiter on public.revenue_hub_entries(recruiter_code);
create index if not exists idx_revenue_hub_interview_date on public.revenue_hub_entries(interview_date);
create index if not exists idx_revenue_hub_joining_date on public.revenue_hub_entries(joining_date);




create index if not exists idx_candidates_updated_at on public.candidates(updated_at);
create index if not exists idx_candidates_recruiter_code on public.candidates(recruiter_code);
create index if not exists idx_candidates_recruiter_name on public.candidates(recruiter_name);
create index if not exists idx_candidates_approval_status on public.candidates(approval_status);
create index if not exists idx_candidates_follow_up_at on public.candidates(follow_up_at);
create index if not exists idx_activity_candidate on public.activity_log(candidate_id, created_at);
create index if not exists idx_activity_created_at on public.activity_log(created_at);
create index if not exists idx_notes_candidate on public.notes(candidate_id, created_at);
create index if not exists idx_notifications_user_status on public.notifications(user_id, status, created_at);
create index if not exists idx_messages_created_at on public.messages(created_at);
create index if not exists idx_messages_thread_key on public.messages(thread_key, created_at);
create index if not exists idx_submissions_candidate_status on public.submissions(candidate_id, approval_status);
create index if not exists idx_candidate_files_candidate on public.candidate_files(candidate_id, file_kind, created_at);
create index if not exists idx_messages_delete_mode on public.messages(delete_mode, thread_key, created_at);
create index if not exists idx_yt_hub_playlists_status on public.yt_hub_playlists(status, updated_at);
create index if not exists idx_yt_hub_videos_playlist on public.yt_hub_videos(playlist_id, status, order_index);
create index if not exists idx_important_resources_status on public.important_resources(status, created_at);

insert into public.users (
  user_id, username, password, full_name, designation, role, recruiter_code,
  assigned_tl_user_id, assigned_tl_name, is_active, theme_name, updated_at
) values (
  'EMP001',
  'manager@careercrox.local',
  'ChangeMe#2026',
  'Career Crox Manager',
  'Manager',
  'manager',
  'MGR-001',
  '',
  '',
  '1',
  'peach-sky',
  now()::text
);

-- Optional: after recruiters self-create IDs, promote a user to TL like this:
-- update public.users set role = 'tl', designation = 'Team Lead' where username = 'someone@example.com';
--
-- Optional: map a recruiter under a TL like this:
-- update public.users
-- set assigned_tl_user_id = 'TL_USER_ID_HERE', assigned_tl_name = 'TL Full Name'
-- where username = 'recruiter@example.com';

-- Restore schema grants after recreating public.
-- Without this, Supabase pooled / API roles can throw `permission denied for schema public`.
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;
grant usage on schema public to public;

grant select, insert, update, delete, truncate, references, trigger on all tables in schema public to anon, authenticated, service_role;
grant usage, select, update on all sequences in schema public to anon, authenticated, service_role;

grant select, insert, update, delete, truncate, references, trigger on all tables in schema public to public;
grant usage, select, update on all sequences in schema public to public;

alter default privileges in schema public grant select, insert, update, delete, truncate, references, trigger on tables to anon, authenticated, service_role;
alter default privileges in schema public grant usage, select, update on sequences to anon, authenticated, service_role;
alter default privileges in schema public grant select, insert, update, delete, truncate, references, trigger on tables to public;
alter default privileges in schema public grant usage, select, update on sequences to public;

